[licenses]
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "Unicode-3.0", "Unicode-DFS-2016", "ISC", "MPL-2.0", "Zlib", "CDLA-Permissive-2.0"]
unused-allowed-license = "allow"

[licenses.private]
ignore = true


[advisories]
ignore = []

[bans]
multiple-versions = "warn"      
wildcards = "deny"             

#  Explicitly ignore only harmless known system-level duplicates and unavoidable nested deps
skip = [
    { name = "getrandom" },
    { name = "hashbrown" },
    { name = "socket2" },
    { name = "axum" },
    { name = "axum-core" },
    { name = "base64" },
    { name = "h2" },
    { name = "http" },
    { name = "http-body" },
    { name = "hyper" },
    { name = "matchit" },
    { name = "thiserror" },
    { name = "thiserror-impl" },
    { name = "tower-http" },
    { name = "windows-sys" }
]
