pub mod config_store;
pub mod crypto;
pub mod daemon;
pub mod errors;
pub mod event_bus;
pub mod mode_controller;
pub mod models;
pub mod paths;
pub mod runtime_api;
pub mod runtime_manager;
pub mod server;
pub mod state;
pub mod state_machine;
pub mod watchdog;

pub use config_store::ConfigStore;
pub use daemon::start_daemon;
pub use errors::RuntimeError;
pub use event_bus::{EventBus, RuntimeEvent};
pub use mode_controller::ModeController;
pub use models::{GuardianConfig, HotspotConfig, RuntimeFlags, RuntimeMode, UplinkConfig};
pub use runtime_api::{ConnectedClient, RuntimeApi, WifiScanResult};
pub use runtime_manager::RuntimeManager;
pub use server::build_wifi_router;
pub use state::{RuntimeStatus, StateMetadata, StateTransition, SystemState};
pub use state_machine::StateMachine;
pub use watchdog::Watchdog;
