// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PeerInfo {
    /// Unique ID for the node (derived from public key)
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// Hostname or device name
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    /// Node IP for P2P communication
    #[prost(string, tag = "3")]
    pub ip_address: ::prost::alloc::string::String,
    /// ECDSA P-256 public key
    #[prost(string, tag = "4")]
    pub public_key: ::prost::alloc::string::String,
    /// Version of running sgx-guardian daemon
    #[prost(string, tag = "5")]
    pub software_version: ::prost::alloc::string::String,
    /// "online", "offline", "attesting", etc.
    #[prost(string, tag = "6")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PolicyInfo {
    /// Unique policy identifier (e.g., UUID)
    #[prost(string, tag = "1")]
    pub policy_id: ::prost::alloc::string::String,
    /// Semantic versioning e.g., "1.0.0"
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// Authority that signed this policy
    #[prost(string, tag = "3")]
    pub signed_by: ::prost::alloc::string::String,
    /// Base64-encoded signature of policy digest
    #[prost(string, tag = "4")]
    pub signature: ::prost::alloc::string::String,
    /// Serialized policy content (YAML or JSON)
    #[prost(bytes = "vec", tag = "5")]
    pub policy_payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingRequest {
    /// who sent the ping
    #[prost(string, tag = "1")]
    pub from: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingResponse {
    /// response text
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
