---
node_id: "nodeA"
hostname: "guardian-node-A"
ip: "0.0.0.0"
port: 50051
public_key: "__GENERATED_AT_FIRST_BOOT__"

api:
  tls:
    enabled: true
    require_https: true
    cert_path: "/var/lib/sgx-guardian/sgx-agent/device_nodeA_cert.der"
    key_path: "/var/lib/sgx-guardian/sgx-agent/device_nodeA.key"
