flowchart TD
 A([Marcus opens Devices tab]) --> B[DV-01 Devices List]
 B --> C[Tap Smart Home Integration banner\npurple gradient button]
 C --> D[DV-11 Smart Home Modal\nHubs tab shown by default]
 D --> E[Tap Start Service]
 E --> F[ Hub integration service started\nGuardian begins scanning for hubs]
 F --> G[Recent Activity log shows:\nHub integration service started 23:00:11]
 G --> H[Tap Discover Hubs]
 H --> I[ Guardian scans local network\nfor smart home hubs]
 I --> J[Recent Activity updates:\nDiscovering hubs on network... 23:00:26]
 J --> K[ Discovered Hubs list appears:\nPhilips Hue Bridge 192.168.1.2\nHome Assistant 192.168.1.100\nHubitat Elevation 192.168.1.150]
 K --> L[Marcus taps Add next to\nPhilips Hue Bridge]
 L --> M[ POST /api/smarthome/hubs\nHub added to Guardian monitoring]
 M --> N[ Toast: Philips Hue Bridge added]
 N --> O[Hub appears in Hubs count\nHubs tab badge: 1]
 O --> P[Marcus switches to Rules tab]
 P --> Q[DV-14 Automation Rules Tab]
 Q --> R[Tap Manage Automation Rules]
 R --> S[Tap Security Triggers card]
 S --> T[Create rule:\nIF threat detected THEN lock doors]
 T --> U[ Rule saved to Guardian]
 U --> V([ Smart home secured\nAutomation active])
