use crate::nebula::overlay::OverlayPool;
use std::fs;
use std::io::Write;
use std::path::Path;

pub struct NebulaConfig;

impl NebulaConfig {
    pub fn generate_config(
        node_name: &str,
        _overlay_ip: &str,
        is_lighthouse: bool,
        config_dir: &str,
    ) -> Result<(), std::io::Error> {
        let config_path = format!("{}/nebula.yaml", config_dir);

        if Path::new(&config_path).exists() {
            println!("ℹ️ Nebula config already exists.");
            return Ok(());
        }

        fs::create_dir_all(config_dir)?;

        let lighthouse_config = if is_lighthouse {
            r#"
lighthouse:
  am_lighthouse: true
  interval: 60
"#
            .to_string()
        } else {
            r#"
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"
"#
            .to_string()
        };

        let config_content = format!(
            r#"
pki:
  ca: "{}/ca/ca.crt"
  cert: "{}/nodes/{}.crt"
  key: "{}/nodes/{}.key"

static_host_map:
  "192.168.100.1": ["YOUR_LIGHTHOUSE_PUBLIC_IP:4242"]

listen:
  host: 0.0.0.0
  port: 4242

firewall:
  outbound:
    - port: any
      proto: any
      host: any

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500

{}

"#,
            config_dir, config_dir, node_name, config_dir, node_name, lighthouse_config
        );

        let mut file = fs::File::create(config_path)?;
        file.write_all(config_content.as_bytes())?;

        println!("✅ Nebula configuration generated.");
        Ok(())
    }

    /// Generate Nebula config with IP from overlay pool.
    /// This replaces the hardcoded IP approach.
    /// The existing generate_config() method is preserved for backward
    /// compatibility but D5 (main.rs) will switch to this method.
    pub fn generate_config_from_pool(
        node_name: &str,
        pool: &OverlayPool,
        config_dir: &str,
    ) -> Result<(), std::io::Error> {
        let config_path = format!("{}/nebula.yaml", config_dir);

        fs::create_dir_all(config_dir)?;

        // Get this node's overlay IP from the pool
        let overlay_ip = pool.get_ip_cidr(node_name).ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!("No overlay IP allocated for {}", node_name),
            )
        })?;

        // Determine if this node is the Circle owner (lighthouse)
        let is_lighthouse = node_name == pool.owner_node;

        // Get the owner's overlay IP for lighthouse config
        let owner_ip = pool
            .get_ip(&pool.owner_node)
            .cloned()
            .unwrap_or_else(|| format!("{}.1", pool.subnet_base));

        // Build lighthouse section
        let lighthouse_section = if is_lighthouse {
            "lighthouse:\n  am_lighthouse: true\n  interval: 60\n".to_string()
        } else {
            format!(
                "lighthouse:\n  am_lighthouse: false\n  interval: 60\n  hosts:\n    - \"{}\"\n",
                owner_ip
            )
        };

        // Build static_host_map section
        let static_host_map = if is_lighthouse {
            "static_host_map: {}\n".to_string()
        } else {
            format!(
                "static_host_map:\n  \"{}\": [\"LIGHTHOUSE_PUBLIC_IP:4242\"]\n",
                owner_ip
            )
        };

        let config_content = format!(
            r#"# Auto-generated by SG-X Guardian Overlay Manager
# Circle: {}
# Node: {} | Overlay IP: {}

pki:
  ca: "{}/ca/ca.crt"
  cert: "{}/nodes/{}.crt"
  key: "{}/nodes/{}.key"

{}
{}
listen:
  host: 0.0.0.0
  port: 4242

tun:
  dev: nebula0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500

firewall:
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      host: any
"#,
            pool.circle_id,
            node_name,
            overlay_ip,
            config_dir,
            config_dir,
            node_name,
            config_dir,
            node_name,
            static_host_map,
            lighthouse_section,
        );

        let mut file = fs::File::create(&config_path)?;
        file.write_all(config_content.as_bytes())?;

        println!(
            "✅ Nebula config generated: {} → {} (tun: nebula0)",
            node_name, overlay_ip
        );
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::nebula::overlay::OverlayPool;

    #[test]
    fn test_generate_config_from_pool_owner() {
        let pool = OverlayPool::new("alpha", "192.168.100", "nodeA");
        let tmp = "/tmp/test_nebula_config_d2";
        let _ = std::fs::create_dir_all(tmp);
        let result = NebulaConfig::generate_config_from_pool("nodeA", &pool, tmp);
        assert!(result.is_ok());
        let content = std::fs::read_to_string(format!("{}/nebula.yaml", tmp)).unwrap();
        assert!(content.contains("am_lighthouse: true"));
        assert!(content.contains("nebula0"));
        assert!(content.contains("192.168.100.1/24"));
        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn test_generate_config_from_pool_member() {
        let mut pool = OverlayPool::new("alpha", "192.168.100", "nodeA");
        pool.allocate("nodeB").unwrap();
        let tmp = "/tmp/test_nebula_config_d2b";
        let _ = std::fs::create_dir_all(tmp);
        let result = NebulaConfig::generate_config_from_pool("nodeB", &pool, tmp);
        assert!(result.is_ok());
        let content = std::fs::read_to_string(format!("{}/nebula.yaml", tmp)).unwrap();
        assert!(content.contains("am_lighthouse: false"));
        assert!(content.contains("192.168.100.1")); // lighthouse host
        assert!(content.contains("192.168.100.2/24")); // member IP
        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn test_generate_config_unallocated_node_fails() {
        let pool = OverlayPool::new("alpha", "192.168.100", "nodeA");
        let tmp = "/tmp/test_nebula_config_d2c";
        let result = NebulaConfig::generate_config_from_pool("nodeZ", &pool, tmp);
        assert!(result.is_err());
        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn test_generate_config_tun_device_is_nebula0() {
        let pool = OverlayPool::new("alpha", "192.168.100", "nodeA");
        let tmp = "/tmp/test_nebula_config_d2d";
        let _ = std::fs::create_dir_all(tmp);
        NebulaConfig::generate_config_from_pool("nodeA", &pool, tmp).unwrap();
        let content = std::fs::read_to_string(format!("{}/nebula.yaml", tmp)).unwrap();
        assert!(content.contains("dev: nebula0"));
        assert!(!content.contains("dev: nebula1")); // old bug must not appear
        let _ = std::fs::remove_dir_all(tmp);
    }
}
