/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xsratgdoaxnaosofvodv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcmF0Z2RvYXhuYW9zb2Z2b2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3NjUyMTAsImV4cCI6MjA4OTM0MTIxMH0.j2knmDvA-X22qD0UOcdrOm-U98zo9-55oARc9_-cYqI"